### ISSUE TITLE
Implement reset behaviour

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_demos#21]
Pressing the button should reset the robot to a state from which the service can be started from the beginning.

@jihoonl already implemented this behaviour for navigation

@bit-pirate will implemented the reseting in the state manager and will send a cancel/reset message to the Android UI. @dwlee please add a subscriber, which will reset the UI to its starting state (ordering screen).

**Comment by jihoonl** [comment]
Reset behavior for ces is implemented and tested before ces.
