### ISSUE TITLE
better parameterS for colour_signal

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_demos#26]
These are the data from experiment in ces.
threshold, window size 
   25       ,        3                        No detects
   24       ,        3                        Sometimes detects
   23       ,        3                        Sometimes detects
   22       ,        3                        Wrong detection
   23       ,        2                        Detects twice from one signal

I couldn't find the right parameter values which work in the ces environment.
I wished to have 2.5 window size....

Also finding the right values require continues testing. It would be nice to have easy way of finding right value.

**Comment by stonier** [comment]
The parameters could be varied alot more widely than in the above. 

There are also other programs in the package which can generate and show you histogram levels from captured images which help understand why it's having trouble in that environment. There must have been alot more ambient green than there was in our office - threshold of 30 was a very safe, conservative threshold.

Might be useful to have a debug runtime output of histogram image streams coming from the node in the future....

**Comment by jihoonl** [comment]
Reopen when we need it again.
