### ISSUE TITLE
migrate vending machine to rocon_devices.

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_demos#42]

**Comment by stonier** [comment]
I initially intended rocon_devices for standard/official devices. This will be a stack we officially release for public consumption so should only include drivers for devices that other people use (e.g. phillips hue) but not our custom experimental devices for demos.

**Comment by bit-pirate** [comment]
What about moving the vending machine there, but put it into a separate branch?

Btw, both the vending machine and automatic door are controlled by an Arduino (Yun). At some point it might be could to have a more generic interface for it. This would then be a good candidate for a release. But I'm still waiting for a good reason for putting in this extra work.

**Comment by jihoonl** [comment]
Both of you are right. Until @bit-pirate finds some time to implement generic arduino yun interface, let's have VM and auto door in separate demo branch since both are useful in more than one demo.

how about `demo_devices` ?

**Comment by stonier** [comment]
I'm guessing it is currently in `rocon_demos`. Is there a reason it doesn't fit there? Awkward dependencies?

**Comment by bit-pirate** [comment]
Auto door is already in rocon devices. Was under the impression that would
be the right place (alongside rocon_hue.) So, will to migrate it.

On Mon, May 26, 2014 at 2:12 PM, Daniel Stonier notifications@github.comwrote:

> I'm guessing it is currently in rocon_demos. Is there a reason it doesn't
> fit there?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/robotics-in-concert/rocon_demos/issues/42#issuecomment-44157807
> .

## 

Innovation Team Leader
Yujin Robot
Seoul, Republic of Korea
Twitter: @yujinrobotinno
Website: http://inno.yujinrobot.com
Email: marcus.liebhardt@yujinrobot.com
Phone: +82-70-46577073

**Comment by jihoonl** [comment]
I meant the branch...

**Comment by jihoonl** [comment]
To conclude,
- migrate auto_door from rocon_devices to rocon_demos
- Keep both on demo_devices branch

All good?

**Comment by bit-pirate** [comment]
:+1:

**Comment by stonier** [comment]
:+1:

**Comment by jihoonl** [comment]
All done. Also note that vendming_machine_control messages are now in rocon_demo_msgs indigo-devel branch.
