### ISSUE TITLE
Migrate hue manager into rocon_devices

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_demos#44]
hue_manager provides generic interface to control a multiple hues. It would be better to stay together with rocon_hue.

https://github.com/robotics-in-concert/rocon_demos/tree/office_concert/office_hue_manager

**Comment by jihoonl** [comment]
Also update set_color to use message format rather than string.

**Comment by dwlee** [comment]
I moved it from office concert and crteated new message for controlling hue color
- [4e0ea2d](https://github.com/robotics-in-concert/rocon_devices/commit/c6d7b331c032055d9a0375e7dc8f4700543c3bba)
- [SetColor](https://github.com/robotics-in-concert/rocon_msgs/blob/indigo/rocon_device_msgs/msg/SetColor.msg)
